# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f7eab31b8304d2eeebc370b111afcd1b9533d1145b9389b8e80d857eaa47e628c15a71e102a9d4227c1ab057ba6aece1247e64d4d5c0ab8c03f3363a4d675df

test:
  secret_key_base: 4ceb762b4d31ac2ee85431c8988cfd6c3aafd7586b16df2caff2f061fd5ce3d7c26483f7c902d594387df20c7d495f0493767d8385bbdab01e822cef7f26650f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
